<?php

use Illuminate\Database\Seeder;
use App\Models\Country;
class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('countries')->delete();

        $countries = array(
            'Afghanistan',
            'Algeria',
            'American Samoa',
            'Angola',
            'Anguilla',
            'Argentina',
            'Armenia',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahrain',
            'Bangladesh',
            'Belarus',
            'Bolivia',
            'Brazil',
            'Brunei',
            'Bulgaria',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Chad',
            'Chile',
            'China',
            'Colombia',
            '"Congo, The Democratic Republic of the"',
            'Czech Republic',
            'Dominican Republic',
            'Ecuador',
            'Egypt',
            'Estonia',
            'Ethiopia',
            'Faroe Islands',
            'Finland',
            'France',
            'French Guiana',
            'French Polynesia',
            'Gambia',
            'Germany',
            'Greece',
            'Greenland',
            'Holy See (Vatican City State)',
            'Hong Kong',
            'Hungary',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Israel',
            'Italy',
            'Japan',
            'Kazakstan',
            'Kenya',
            'Kuwait',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Mexico',
            'Moldova',
            'Morocco',
            'Mozambique',
            'Myanmar',
            'Nauru',
            'Nepal',
            'Netherlands',
            'New Zealand',
            'Nigeria',
            'North Korea',
            'Oman',
            'Pakistan',
            'Paraguay',
            'Peru',
            'Philippines',
            'Poland',
            'Puerto Rico',
            'Romania',
            'Runion',
            'Russian Federation',
            'Saint Vincent and the Grenadines',
            'Saudi Arabia',
            'Senegal',
            'Slovakia',
            'South Africa',
            'South Korea',
            'Spain',
            'Sri Lanka',
            'Sudan',
            'Sweden',
            'Switzerland',
            'Taiwan',
            'Tanzania',
            'Thailand',
            'Tonga',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Tuvalu',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'United States',
            'Venezuela',
            'Vietnam',
            '"Virgin Islands, U.S."',
            'Yemen',
            'Yugoslavia',
            'Zambia',
        );

        foreach ($countries as $country) {
            Country::create([
                'name' => $country
            ]);
        }
    }
}
